# Generated by Django 3.2.12 on 2022-02-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewsPost', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
