# Generated by Django 3.2.12 on 2022-02-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_published_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
