# Generated by Django 3.2.12 on 2022-02-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_news_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-published_date']},
        ),
    ]
