# Generated by Django 3.2.12 on 2022-02-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_galery_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='Book',
            field=models.FileField(default=1, upload_to='Book/%Y-%m-%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galery',
            name='Photo',
            field=models.ImageField(upload_to='galery/'),
        ),
    ]
