# Generated by Django 3.2.12 on 2022-02-17 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220217_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galery',
            name='Book',
        ),
        migrations.AddField(
            model_name='galery',
            name='advert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.galery'),
            preserve_default=False,
        ),
    ]
