# Generated by Django 3.2.12 on 2022-02-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220217_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galery',
            name='advert',
        ),
    ]
